export const contactSeeds = [
  {
    id: "contact-marketplaces-general",
    area: "Marketplaces",
    name: "MARKETPLACES",
    email: "",
    whatsapp: "+52 56 2600 0811",
    schedule: "Lun-Vie 10:00-17:30; Sab 10:00-16:30",
    description: "Marketplaces, seguimiento a pedidos y atencion directa para clientes.",
    channels: ["whatsapp_cloud", "evolution_api", "telnyx", "plivo"],
    intents: ["marketplace_support"],
    marketplaces: ["marketplace", "walmart", "elektra", "liverpool", "marti", "temu", "coppel", "tiktok"],
    skills: ["marketplaces"],
    priority: 50,
    active: true
  },
  {
    id: "contact-mercado-libre",
    area: "Marketplaces",
    name: "Mercado Libre",
    email: "",
    whatsapp: "+52 55 5289 9999, +52 56 3998 8805",
    schedule: "Lun-Vie 10:00-17:30; Sab 10:00-16:30",
    description: "Marketplaces, seguimiento a pedidos y atencion directa para clientes de Mercado Libre.",
    channels: ["whatsapp_cloud", "evolution_api", "telnyx", "plivo"],
    intents: ["marketplace_support"],
    marketplaces: ["mercadolibre", "mercado libre"],
    skills: ["mercadolibre", "marketplaces"],
    priority: 10,
    active: true
  },
  {
    id: "contact-amazon",
    area: "Marketplaces",
    name: "Amazon",
    email: "",
    whatsapp: "+52 56 3967 7777",
    schedule: "Lun-Vie 10:00-17:30; Sab 10:00-16:30",
    description: "Marketplaces, seguimiento a pedidos y atencion directa para clientes de Amazon.",
    channels: ["whatsapp_cloud", "evolution_api", "telnyx", "plivo"],
    intents: ["marketplace_support"],
    marketplaces: ["amazon"],
    skills: ["amazon", "marketplaces"],
    priority: 10,
    active: true
  },
  {
    id: "contact-centro-servicios-dr-vertiz",
    area: "Servicios",
    name: "Centro de servicios Dr. Vertiz",
    email: "",
    whatsapp: "+52 56 2188 8866, +52 56 3061 1888, +52 56 1388 8866, +52 56 3976 6666",
    schedule: "Lun-Vie 10:00-17:30; Sab 10:00-16:30",
    description: "Garantias, reparaciones, fallas tecnicas y refacciones.",
    channels: ["web_widget", "official_site", "whatsapp_cloud", "evolution_api"],
    intents: ["appointment", "technical_support", "warranty"],
    marketplaces: [],
    skills: ["garantias", "reparaciones", "servicio", "atc"],
    priority: 10,
    active: true
  },
  {
    id: "contact-pino-suarez",
    area: "Servicios",
    name: "Pino Suarez",
    email: "",
    whatsapp: "+52 56 3088 8801",
    schedule: "Lun-Dom 11:00-20:00",
    description: "Garantias, reparaciones, fallas tecnicas y refacciones.",
    channels: ["web_widget", "official_site", "whatsapp_cloud", "evolution_api"],
    intents: ["appointment", "technical_support", "warranty"],
    marketplaces: [],
    skills: ["garantias", "reparaciones", "servicio", "atc"],
    priority: 20,
    active: true
  },
  {
    id: "contact-insurgentes-sur-539",
    area: "Sucursal",
    name: "Insurgentes Sur 539",
    email: "",
    whatsapp: "+52 55 3262 6718",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-insurgentes-sur-1618",
    area: "Sucursal",
    name: "Insurgentes Sur 1618",
    email: "",
    whatsapp: "+52 56 3988 8828",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-genova",
    area: "Sucursal",
    name: "Genova",
    email: "",
    whatsapp: "+52 56 3998 8880",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-san-pablo-9",
    area: "Sucursal",
    name: "San Pablo 9",
    email: "",
    whatsapp: "+52 55 8088 2083",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-izazaga-8",
    area: "Sucursal",
    name: "Izazaga 8",
    email: "",
    whatsapp: "+52 56 3969 9999",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-zona-rosa",
    area: "Sucursal",
    name: "Zona Rosa",
    email: "",
    whatsapp: "+52 56 2068 8889",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-masaryk",
    area: "Sucursal",
    name: "Masaryk",
    email: "",
    whatsapp: "+52 56 3088 8800",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-izazaga-1",
    area: "Sucursal",
    name: "Izazaga 1",
    email: "",
    whatsapp: "+52 56 3969 9999",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-aguascalientes",
    area: "Sucursal",
    name: "Aguascalientes",
    email: "",
    whatsapp: "+52 44 9181 0088",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-san-cristobal-de-las-casas",
    area: "Sucursal",
    name: "San Cristobal de las Casas",
    email: "",
    whatsapp: "+52 96 7345 5263",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-franquicia-ecatepec",
    area: "Sucursal",
    name: "Franquicia Ecatepec",
    email: "",
    whatsapp: "+52 56 3000 7995",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-vallarta",
    area: "Sucursal",
    name: "Vallarta",
    email: "",
    whatsapp: "+52 33 2609 8139",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-16-de-septiembre",
    area: "Sucursal",
    name: "16 de Septiembre",
    email: "",
    whatsapp: "+52 33 2609 8139",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-colon",
    area: "Sucursal",
    name: "Colon",
    email: "",
    whatsapp: "+52 33 2615 2786",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-shoptown",
    area: "Sucursal",
    name: "Shoptown",
    email: "",
    whatsapp: "+52 81 4049 6010",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-tec",
    area: "Sucursal",
    name: "Tec",
    email: "",
    whatsapp: "+52 81 4049 6010",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-san-agustin",
    area: "Sucursal",
    name: "San Agustin",
    email: "",
    whatsapp: "+52 81 4049 6010",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-puebla",
    area: "Sucursal",
    name: "Puebla",
    email: "",
    whatsapp: "+52 22 2722 8888",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-universidad-oriente",
    area: "Sucursal",
    name: "Universidad Oriente",
    email: "",
    whatsapp: "+52 44 2314 7513",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-ubika",
    area: "Sucursal",
    name: "Ubika",
    email: "",
    whatsapp: "+52 44 6200 0996",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-queretaro-de-la-cruz",
    area: "Sucursal",
    name: "Queretaro de la Cruz",
    email: "",
    whatsapp: "+52 44 6200 1054",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-universidad",
    area: "Sucursal",
    name: "Universidad",
    email: "",
    whatsapp: "+52 44 2212 3223",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  },
  {
    id: "contact-merida",
    area: "Sucursal",
    name: "Merida",
    email: "",
    whatsapp: "+52 99 9484 9837",
    schedule: "Lun-Sab 10:30-19:00; Dom 12:00-18:00",
    description: "Tienda fisica para venta y atencion a cliente.",
    channels: ["web_widget", "official_site", "whatsapp_cloud"],
    intents: ["faq", "sales", "appointment"],
    marketplaces: [],
    skills: ["ventas", "atc", "sucursal"],
    priority: 100,
    active: true
  }
];
